/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

import { getPowerSdkInstance } from '@pa-client/power-code-sdk/lib/';
import { dataSourcesInfo } from '../../.power/appschemas/dataSourcesInfo';
import type { DataSourcesInfo, IOperationResult } from '@pa-client/power-code-sdk/lib/';
import { projecthub_sp_SearchTasksResponse } from '../Models/projecthub_sp_SearchTasksModel';

export class projecthub_sp_SearchTasksService {
  private static readonly dataSourceName = 'YOUR_DATABASE_NAME';

  public static async projecthub_sp_SearchTasks(AssignedTo?: string, DueDateFrom?: string, DueDateTo?: string, IncludeCompleted?: boolean, PageNumber?: number, PageSize?: number, Priority?: string, ProjectId?: number, SearchTerm?: string, SortColumn?: string, SortDirection?: string, Status?: string, TotalRecords?: number): Promise<IOperationResult<projecthub_sp_SearchTasksResponse>> {
    const parameters: { AssignedTo?: string, DueDateFrom?: string, DueDateTo?: string, IncludeCompleted?: boolean, PageNumber?: number, PageSize?: number, Priority?: string, ProjectId?: number, SearchTerm?: string, SortColumn?: string, SortDirection?: string, Status?: string, TotalRecords?: number } = { AssignedTo, DueDateFrom, DueDateTo, IncludeCompleted, PageNumber, PageSize, Priority, ProjectId, SearchTerm, SortColumn, SortDirection, Status, TotalRecords };
    const result = await getPowerSdkInstance(dataSourcesInfo as unknown as DataSourcesInfo).Data.executeAsync<{ AssignedTo?: string, DueDateFrom?: string, DueDateTo?: string, IncludeCompleted?: boolean, PageNumber?: number, PageSize?: number, Priority?: string, ProjectId?: number, SearchTerm?: string, SortColumn?: string, SortDirection?: string, Status?: string, TotalRecords?: number }, projecthub_sp_SearchTasksResponse>({
      connectorOperation: {
        tableName: projecthub_sp_SearchTasksService.dataSourceName,
        operationName: '/projecthub.sp_SearchTasks',
        parameters
      },
    });
    return result;
  }
}

