/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

import { getPowerSdkInstance } from '@pa-client/power-code-sdk/lib/';
import { dataSourcesInfo } from '../../.power/appschemas/dataSourcesInfo';
import type { DataSourcesInfo, IOperationResult } from '@pa-client/power-code-sdk/lib/';
import { projecthub_sp_GetProjectProgressResponse } from '../Models/projecthub_sp_GetProjectProgressModel';

export class projecthub_sp_GetProjectProgressService {
  private static readonly dataSourceName = 'YOUR_DATABASE_NAME';

  public static async projecthub_sp_GetProjectProgress(): Promise<IOperationResult<projecthub_sp_GetProjectProgressResponse>> {
    const result = await getPowerSdkInstance(dataSourcesInfo as unknown as DataSourcesInfo).Data.executeAsync<void, projecthub_sp_GetProjectProgressResponse>({
      connectorOperation: {
        tableName: projecthub_sp_GetProjectProgressService.dataSourceName,
        operationName: '/projecthub.sp_GetProjectProgress',
      },
    });
    return result;
  }
}

