/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

import { getPowerSdkInstance } from '@pa-client/power-code-sdk/lib/';
import { dataSourcesInfo } from '../../.power/appschemas/dataSourcesInfo';
import type { DataSourcesInfo, IOperationResult } from '@pa-client/power-code-sdk/lib/';
import { projecthub_sp_GetRecentActivityResponse } from '../Models/projecthub_sp_GetRecentActivityModel';

export class projecthub_sp_GetRecentActivityService {
  private static readonly dataSourceName = 'YOUR_DATABASE_NAME';

  public static async projecthub_sp_GetRecentActivity(): Promise<IOperationResult<projecthub_sp_GetRecentActivityResponse>> {
    const result = await getPowerSdkInstance(dataSourcesInfo as unknown as DataSourcesInfo).Data.executeAsync<void, projecthub_sp_GetRecentActivityResponse>({
      connectorOperation: {
        tableName: projecthub_sp_GetRecentActivityService.dataSourceName,
        operationName: '/projecthub.sp_GetRecentActivity',
      },
    });
    return result;
  }
}

