/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

import { getPowerSdkInstance } from '@pa-client/power-code-sdk/lib/';
import { dataSourcesInfo } from '../../.power/appschemas/dataSourcesInfo';
import type { DataSourcesInfo, IOperationResult } from '@pa-client/power-code-sdk/lib/';
import { projecthub_sp_UpdateClientResponse } from '../Models/projecthub_sp_UpdateClientModel';

export class projecthub_sp_UpdateClientService {
  private static readonly dataSourceName = 'YOUR_DATABASE_NAME';

  public static async projecthub_sp_UpdateClient(Address?: string, City?: string, Company?: string, ContactPerson?: string, Country?: string, Email?: string, Id?: number, Industry?: string, Name?: string, Notes?: string, Phone?: string, State?: string, Status?: string, ZipCode?: string): Promise<IOperationResult<projecthub_sp_UpdateClientResponse>> {
    const parameters: { Address?: string, City?: string, Company?: string, ContactPerson?: string, Country?: string, Email?: string, Id?: number, Industry?: string, Name?: string, Notes?: string, Phone?: string, State?: string, Status?: string, ZipCode?: string } = { Address, City, Company, ContactPerson, Country, Email, Id, Industry, Name, Notes, Phone, State, Status, ZipCode };
    const result = await getPowerSdkInstance(dataSourcesInfo as unknown as DataSourcesInfo).Data.executeAsync<{ Address?: string, City?: string, Company?: string, ContactPerson?: string, Country?: string, Email?: string, Id?: number, Industry?: string, Name?: string, Notes?: string, Phone?: string, State?: string, Status?: string, ZipCode?: string }, projecthub_sp_UpdateClientResponse>({
      connectorOperation: {
        tableName: projecthub_sp_UpdateClientService.dataSourceName,
        operationName: '/projecthub.sp_UpdateClient',
        parameters
      },
    });
    return result;
  }
}
