/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

import { getPowerSdkInstance } from '@pa-client/power-code-sdk/lib/';
import { dataSourcesInfo } from '../../.power/appschemas/dataSourcesInfo';
import type { DataSourcesInfo, IOperationResult } from '@pa-client/power-code-sdk/lib/';
import { projecthub_sp_SearchProjectsResponse } from '../Models/projecthub_sp_SearchProjectsModel';

export class projecthub_sp_SearchProjectsService {
  private static readonly dataSourceName = 'YOUR_DATABASE_NAME';

  public static async projecthub_sp_SearchProjects(ClientId?: number, PageNumber?: number, PageSize?: number, Priority?: string, SearchTerm?: string, SortColumn?: string, SortDirection?: string, StartDateFrom?: string, StartDateTo?: string, Status?: string, TotalRecords?: number): Promise<IOperationResult<projecthub_sp_SearchProjectsResponse>> {
    const parameters: { ClientId?: number, PageNumber?: number, PageSize?: number, Priority?: string, SearchTerm?: string, SortColumn?: string, SortDirection?: string, StartDateFrom?: string, StartDateTo?: string, Status?: string, TotalRecords?: number } = { ClientId, PageNumber, PageSize, Priority, SearchTerm, SortColumn, SortDirection, StartDateFrom, StartDateTo, Status, TotalRecords };
    const result = await getPowerSdkInstance(dataSourcesInfo as unknown as DataSourcesInfo).Data.executeAsync<{ ClientId?: number, PageNumber?: number, PageSize?: number, Priority?: string, SearchTerm?: string, SortColumn?: string, SortDirection?: string, StartDateFrom?: string, StartDateTo?: string, Status?: string, TotalRecords?: number }, projecthub_sp_SearchProjectsResponse>({
      connectorOperation: {
        tableName: projecthub_sp_SearchProjectsService.dataSourceName,
        operationName: '/projecthub.sp_SearchProjects',
        parameters
      },
    });
    return result;
  }
}

