/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

import { getPowerSdkInstance } from '@pa-client/power-code-sdk/lib/';
import { dataSourcesInfo } from '../../.power/appschemas/dataSourcesInfo';
import type { DataSourcesInfo, IOperationResult } from '@pa-client/power-code-sdk/lib/';
import { projecthub_sp_CreateProjectResponse } from '../Models/projecthub_sp_CreateProjectModel';

export class projecthub_sp_CreateProjectService {
  private static readonly dataSourceName = 'YOUR_DATABASE_NAME';

  public static async projecthub_sp_CreateProject(Budget?: number, ClientId?: number, Description?: string, EndDate?: string, EstimatedHours?: number, Name?: string, Priority?: string, StartDate?: string, Status?: string): Promise<IOperationResult<projecthub_sp_CreateProjectResponse>> {
    const parameters: { Budget?: number, ClientId?: number, Description?: string, EndDate?: string, EstimatedHours?: number, Name?: string, Priority?: string, StartDate?: string, Status?: string } = { Budget, ClientId, Description, EndDate, EstimatedHours, Name, Priority, StartDate, Status };
    const result = await getPowerSdkInstance(dataSourcesInfo as unknown as DataSourcesInfo).Data.executeAsync<{ Budget?: number, ClientId?: number, Description?: string, EndDate?: string, EstimatedHours?: number, Name?: string, Priority?: string, StartDate?: string, Status?: string }, projecthub_sp_CreateProjectResponse>({
      connectorOperation: {
        tableName: projecthub_sp_CreateProjectService.dataSourceName,
        operationName: '/projecthub.sp_CreateProject',
        parameters
      },
    });
    return result;
  }
}

