/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

import { getPowerSdkInstance } from '@pa-client/power-code-sdk/lib/';
import { dataSourcesInfo } from '../../.power/appschemas/dataSourcesInfo';
import type { DataSourcesInfo, IOperationResult } from '@pa-client/power-code-sdk/lib/';
import { projecthub_sp_CreateTaskResponse } from '../Models/projecthub_sp_CreateTaskModel';

export class projecthub_sp_CreateTaskService {
  private static readonly dataSourceName = 'YOUR_DATABASE_NAME';

  public static async projecthub_sp_CreateTask(AssignedTo?: string, Description?: string, DueDate?: string, EndDate?: string, EstimatedHours?: number, ParentTaskId?: number, PredecessorIds?: string, Priority?: string, Progress?: number, ProjectId?: number, StartDate?: string, Status?: string, TaskOrder?: number, Title?: string): Promise<IOperationResult<projecthub_sp_CreateTaskResponse>> {
    const parameters: { AssignedTo?: string, Description?: string, DueDate?: string, EndDate?: string, EstimatedHours?: number, ParentTaskId?: number, PredecessorIds?: string, Priority?: string, Progress?: number, ProjectId?: number, StartDate?: string, Status?: string, TaskOrder?: number, Title?: string } = { AssignedTo, Description, DueDate, EndDate, EstimatedHours, ParentTaskId, PredecessorIds, Priority, Progress, ProjectId, StartDate, Status, TaskOrder, Title };
    const result = await getPowerSdkInstance(dataSourcesInfo as unknown as DataSourcesInfo).Data.executeAsync<{ AssignedTo?: string, Description?: string, DueDate?: string, EndDate?: string, EstimatedHours?: number, ParentTaskId?: number, PredecessorIds?: string, Priority?: string, Progress?: number, ProjectId?: number, StartDate?: string, Status?: string, TaskOrder?: number, Title?: string }, projecthub_sp_CreateTaskResponse>({
      connectorOperation: {
        tableName: projecthub_sp_CreateTaskService.dataSourceName,
        operationName: '/projecthub.sp_CreateTask',
        parameters
      },
    });
    return result;
  }
}

