/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

import { getPowerSdkInstance } from '@pa-client/power-code-sdk/lib/';
import { dataSourcesInfo } from '../../.power/appschemas/dataSourcesInfo';
import type { DataSourcesInfo, IOperationResult } from '@pa-client/power-code-sdk/lib/';
import { projecthub_sp_ReorderTaskResponse } from '../Models/projecthub_sp_ReorderTaskModel';

export class projecthub_sp_ReorderTaskService {
  private static readonly dataSourceName = 'YOUR_DATABASE_NAME';

  public static async projecthub_sp_ReorderTask(NewPosition?: number, ParentTaskId?: number, ProjectId?: number, TaskId?: number): Promise<IOperationResult<projecthub_sp_ReorderTaskResponse>> {
    const parameters: { NewPosition?: number, ParentTaskId?: number, ProjectId?: number, TaskId?: number } = { NewPosition, ParentTaskId, ProjectId, TaskId };
    const result = await getPowerSdkInstance(dataSourcesInfo as unknown as DataSourcesInfo).Data.executeAsync<{ NewPosition?: number, ParentTaskId?: number, ProjectId?: number, TaskId?: number }, projecthub_sp_ReorderTaskResponse>({
      connectorOperation: {
        tableName: projecthub_sp_ReorderTaskService.dataSourceName,
        operationName: '/projecthub.sp_ReorderTask',
        parameters
      },
    });
    return result;
  }
}
