/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

import { getPowerSdkInstance } from '@pa-client/power-code-sdk/lib/';
import { dataSourcesInfo } from '../../.power/appschemas/dataSourcesInfo';
import type { DataSourcesInfo, IOperationResult } from '@pa-client/power-code-sdk/lib/';
import { projecthub_sp_SearchClientsResponse } from '../Models/projecthub_sp_SearchClientsModel';

export class projecthub_sp_SearchClientsService {
  private static readonly dataSourceName = 'YOUR_DATABASE_NAME';

  public static async projecthub_sp_SearchClients(CompanyFilter?: string, PageNumber?: number, PageSize?: number, SearchTerm?: string, SortColumn?: string, SortDirection?: string, Status?: string, TotalRecords?: number): Promise<IOperationResult<projecthub_sp_SearchClientsResponse>> {
    const parameters: { CompanyFilter?: string, PageNumber?: number, PageSize?: number, SearchTerm?: string, SortColumn?: string, SortDirection?: string, Status?: string, TotalRecords?: number } = { CompanyFilter, PageNumber, PageSize, SearchTerm, SortColumn, SortDirection, Status, TotalRecords };
    const result = await getPowerSdkInstance(dataSourcesInfo as unknown as DataSourcesInfo).Data.executeAsync<{ CompanyFilter?: string, PageNumber?: number, PageSize?: number, SearchTerm?: string, SortColumn?: string, SortDirection?: string, Status?: string, TotalRecords?: number }, projecthub_sp_SearchClientsResponse>({
      connectorOperation: {
        tableName: projecthub_sp_SearchClientsService.dataSourceName,
        operationName: '/projecthub.sp_SearchClients',
        parameters
      },
    });
    return result;
  }
}
