/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

import { getPowerSdkInstance } from '@pa-client/power-code-sdk/lib/';
import { dataSourcesInfo } from '../../.power/appschemas/dataSourcesInfo';
import type { DataSourcesInfo, IOperationResult } from '@pa-client/power-code-sdk/lib/';
import { projecthub_sp_GetAllTasksResponse } from '../Models/projecthub_sp_GetAllTasksModel';

export class projecthub_sp_GetAllTasksService {
  private static readonly dataSourceName = 'YOUR_DATABASE_NAME';

  public static async projecthub_sp_GetAllTasks(): Promise<IOperationResult<projecthub_sp_GetAllTasksResponse>> {
    const result = await getPowerSdkInstance(dataSourcesInfo as unknown as DataSourcesInfo).Data.executeAsync<void, projecthub_sp_GetAllTasksResponse>({
      connectorOperation: {
        tableName: projecthub_sp_GetAllTasksService.dataSourceName,
        operationName: '/projecthub.sp_GetAllTasks',
      },
    });
    return result;
  }
}

