/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

import { getPowerSdkInstance } from '@pa-client/power-code-sdk/lib/';
import { dataSourcesInfo } from '../../.power/appschemas/dataSourcesInfo';
import type { DataSourcesInfo, IOperationResult } from '@pa-client/power-code-sdk/lib/';
import { projecthub_sp_GetAllClientsResponse } from '../Models/projecthub_sp_GetAllClientsModel';

export class projecthub_sp_GetAllClientsService {
  private static readonly dataSourceName = 'YOUR_DATABASE_NAME';

  public static async projecthub_sp_GetAllClients(): Promise<IOperationResult<projecthub_sp_GetAllClientsResponse>> {
    const result = await getPowerSdkInstance(dataSourcesInfo as unknown as DataSourcesInfo).Data.executeAsync<void, projecthub_sp_GetAllClientsResponse>({
      connectorOperation: {
        tableName: projecthub_sp_GetAllClientsService.dataSourceName,
        operationName: '/projecthub.sp_GetAllClients',
      },
    });
    return result;
  }
}
