/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

import { getPowerSdkInstance } from '@pa-client/power-code-sdk/lib/';
import { dataSourcesInfo } from '../../.power/appschemas/dataSourcesInfo';
import type { DataSourcesInfo, IOperationResult } from '@pa-client/power-code-sdk/lib/';
import { projecthub_sp_GetTaskByIdResponse } from '../Models/projecthub_sp_GetTaskByIdModel';

export class projecthub_sp_GetTaskByIdService {
  private static readonly dataSourceName = 'YOUR_DATABASE_NAME';

  public static async projecthub_sp_GetTaskById(Id?: number): Promise<IOperationResult<projecthub_sp_GetTaskByIdResponse>> {
    const parameters: { Id?: number } = { Id };
    const result = await getPowerSdkInstance(dataSourcesInfo as unknown as DataSourcesInfo).Data.executeAsync<{ Id?: number }, projecthub_sp_GetTaskByIdResponse>({
      connectorOperation: {
        tableName: projecthub_sp_GetTaskByIdService.dataSourceName,
        operationName: '/projecthub.sp_GetTaskById',
        parameters
      },
    });
    return result;
  }
}

