/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

import { getPowerSdkInstance } from '@pa-client/power-code-sdk/lib/';
import { dataSourcesInfo } from '../../.power/appschemas/dataSourcesInfo';
import type { DataSourcesInfo, IOperationResult } from '@pa-client/power-code-sdk/lib/';
import { projecthub_sp_GetClientByIdResponse } from '../Models/projecthub_sp_GetClientByIdModel';

export class projecthub_sp_GetClientByIdService {
  private static readonly dataSourceName = 'YOUR_DATABASE_NAME';

  public static async projecthub_sp_GetClientById(Id?: number): Promise<IOperationResult<projecthub_sp_GetClientByIdResponse>> {
    const parameters: { Id?: number } = { Id };
    const result = await getPowerSdkInstance(dataSourcesInfo as unknown as DataSourcesInfo).Data.executeAsync<{ Id?: number }, projecthub_sp_GetClientByIdResponse>({
      connectorOperation: {
        tableName: projecthub_sp_GetClientByIdService.dataSourceName,
        operationName: '/projecthub.sp_GetClientById',
        parameters
      },
    });
    return result;
  }
}
