/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

import { getPowerSdkInstance } from '@pa-client/power-code-sdk/lib/';
import { dataSourcesInfo } from '../../.power/appschemas/dataSourcesInfo';
import type { DataSourcesInfo, IOperationResult } from '@pa-client/power-code-sdk/lib/';
import { projecthub_sp_UpdateTaskResponse } from '../Models/projecthub_sp_UpdateTaskModel';

export class projecthub_sp_UpdateTaskService {
  private static readonly dataSourceName = 'YOUR_DATABASE_NAME';

  public static async projecthub_sp_UpdateTask(ActualHours?: number, AssignedTo?: string, Description?: string, DueDate?: string, EndDate?: string, EstimatedHours?: number, Id?: number, ParentTaskId?: number, PredecessorIds?: string, Priority?: string, Progress?: number, ProjectId?: number, StartDate?: string, Status?: string, TaskOrder?: number, Title?: string): Promise<IOperationResult<projecthub_sp_UpdateTaskResponse>> {
    const parameters: { ActualHours?: number, AssignedTo?: string, Description?: string, DueDate?: string, EndDate?: string, EstimatedHours?: number, Id?: number, ParentTaskId?: number, PredecessorIds?: string, Priority?: string, Progress?: number, ProjectId?: number, StartDate?: string, Status?: string, TaskOrder?: number, Title?: string } = { ActualHours, AssignedTo, Description, DueDate, EndDate, EstimatedHours, Id, ParentTaskId, PredecessorIds, Priority, Progress, ProjectId, StartDate, Status, TaskOrder, Title };
    const result = await getPowerSdkInstance(dataSourcesInfo as unknown as DataSourcesInfo).Data.executeAsync<{ ActualHours?: number, AssignedTo?: string, Description?: string, DueDate?: string, EndDate?: string, EstimatedHours?: number, Id?: number, ParentTaskId?: number, PredecessorIds?: string, Priority?: string, Progress?: number, ProjectId?: number, StartDate?: string, Status?: string, TaskOrder?: number, Title?: string }, projecthub_sp_UpdateTaskResponse>({
      connectorOperation: {
        tableName: projecthub_sp_UpdateTaskService.dataSourceName,
        operationName: '/projecthub.sp_UpdateTask',
        parameters
      },
    });
    return result;
  }
}

