/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

import { getPowerSdkInstance } from '@pa-client/power-code-sdk/lib/';
import { dataSourcesInfo } from '../../.power/appschemas/dataSourcesInfo';
import type { DataSourcesInfo, IOperationResult } from '@pa-client/power-code-sdk/lib/';
import { projecthub_sp_GetUpcomingDeadlinesResponse } from '../Models/projecthub_sp_GetUpcomingDeadlinesModel';

export class projecthub_sp_GetUpcomingDeadlinesService {
  private static readonly dataSourceName = 'YOUR_DATABASE_NAME';

  public static async projecthub_sp_GetUpcomingDeadlines(): Promise<IOperationResult<projecthub_sp_GetUpcomingDeadlinesResponse>> {
    const result = await getPowerSdkInstance(dataSourcesInfo as unknown as DataSourcesInfo).Data.executeAsync<void, projecthub_sp_GetUpcomingDeadlinesResponse>({
      connectorOperation: {
        tableName: projecthub_sp_GetUpcomingDeadlinesService.dataSourceName,
        operationName: '/projecthub.sp_GetUpcomingDeadlines',
      },
    });
    return result;
  }
}

