SELECT TOP (1000) [Id]
      ,[Title]
      ,[Description]
      ,[ProjectId]
      ,[ParentTaskId]
      ,[PredecessorIds]
      ,[AssignedTo]
      ,[Status]
      ,[Priority]
      ,[StartDate]
      ,[EndDate]
      ,[DueDate]
      ,[EstimatedHours]
      ,[ActualHours]
      ,[Progress]
      ,[TaskOrder]
      ,[CreatedDate]
      ,[LastModified]
  FROM [projecthub].[Tasks] Where ProjectId = 1
  