/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

export interface projecthub_sp_UpdateClientRequest {
  Address?: string;
  City?: string;
  Company?: string;
  ContactPerson?: string;
  Country?: string;
  Email?: string;
  Id?: number;
  Industry?: string;
  Name?: string;
  Notes?: string;
  Phone?: string;
  State?: string;
  Status?: string;
  ZipCode?: string;
}

export interface projecthub_sp_UpdateClientResponse {
  returncode?: number;
  outputparameters?: Record<string, unknown>;
  ResultSets?: {
    Table1?: {
      Id?: number;
      Name?: string;
      ContactPerson?: string;
      Email?: string;
      Phone?: string;
      Company?: string;
      Address?: string;
      City?: string;
      State?: string;
      ZipCode?: string;
      Country?: string;
      Industry?: string;
      Notes?: string;
      Status?: string;
      CreatedDate?: string;
      LastModified?: string;
      ProjectCount?: number;
    }[];
  };
}
