/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

export interface projecthub_sp_GetProjectByIdRequest {
  Id?: number;
}

export interface projecthub_sp_GetProjectByIdResponse {
  returncode?: number;
  outputparameters?: Record<string, unknown>;
  ResultSets?: {
    Table1?: {
      Id?: number;
      Name?: string;
      Description?: string;
      ClientId?: number;
      ClientName?: string;
      Status?: string;
      Priority?: string;
      StartDate?: string;
      EndDate?: string;
      EstimatedHours?: number;
      ActualHours?: number;
      Budget?: number;
      Progress?: number;
      CreatedDate?: string;
      LastModified?: string;
      TaskCount?: number;
      CompletedTaskCount?: number;
    }[];
  };
}
