/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

export interface projecthub_sp_SearchTasksRequest {
  AssignedTo?: string;
  DueDateFrom?: string;
  DueDateTo?: string;
  IncludeCompleted?: boolean;
  PageNumber?: number;
  PageSize?: number;
  Priority?: string;
  ProjectId?: number;
  SearchTerm?: string;
  SortColumn?: string;
  SortDirection?: string;
  Status?: string;
  TotalRecords?: number;
}

export interface projecthub_sp_SearchTasksResponse {
  returncode?: number;
  outputparameters?: {
    TotalRecords?: number;
  };
  ResultSets?: {
    Table1?: {
      Id?: number;
      Title?: string;
      Description?: string;
      ProjectId?: number;
      ProjectName?: string;
      ParentTaskId?: number;
      PredecessorIds?: string;
      AssignedTo?: string;
      Status?: string;
      Priority?: string;
      StartDate?: string;
      EndDate?: string;
      DueDate?: string;
      EstimatedHours?: number;
      ActualHours?: number;
      Progress?: number;
      TaskOrder?: number;
      CreatedDate?: string;
      LastModified?: string;
      HasChildren?: number;
      Level?: number;
    };
  };
}
