/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

export interface projecthub_sp_GetClientByIdRequest {
  Id?: number;
}

export interface projecthub_sp_GetClientByIdResponse {
  returncode?: number;
  outputparameters?: Record<string, unknown>;
  ResultSets?: {
    Table1?: {
      Id?: number;
      Name?: string;
      ContactPerson?: string;
      Email?: string;
      Phone?: string;
      Company?: string;
      Address?: string;
      City?: string;
      State?: string;
      ZipCode?: string;
      Country?: string;
      Industry?: string;
      Notes?: string;
      Status?: string;
      CreatedDate?: string;
      LastModified?: string;
      ProjectCount?: number;
    }[];
  };
}
