/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

export type projecthub_sp_GetAllClientsRequest = Record<string, unknown>;

export interface projecthub_sp_GetAllClientsResponse {
  returncode?: number;
  outputparameters?: Record<string, unknown>;
  ResultSets?: {
    Table1?: {
      Id?: number;
      Name?: string;
      ContactPerson?: string;
      Email?: string;
      Status?: string;
    };
  };
}
