/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

export type projecthub_sp_GetDashboardStatsRequest = Record<string, unknown>;

export interface projecthub_sp_GetDashboardStatsResponse {
  returncode?: number;
  outputparameters?: Record<string, unknown>;
  ResultSets?: {
    Table1?: {
      ActiveClients?: number;
      ActiveProjects?: number;
      PendingTasks?: number;
      CompletedTasks?: number;
      AverageProjectProgress?: number;
      TotalActiveBudget?: number;
    }[];
  };
}
