/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

export interface projecthub_sp_DeleteClientRequest {
  Id?: number;
}

export interface projecthub_sp_DeleteClientResponse {
  returncode?: number;
  outputparameters?: Record<string, unknown>;
  ResultSets?: {
    Table1?: {
      DeletedRows?: number;
    };
  };
}
