/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

export interface projecthub_sp_UpdateTaskRequest {
  ActualHours?: number;
  AssignedTo?: string;
  Description?: string;
  DueDate?: string;
  EndDate?: string;
  EstimatedHours?: number;
  Id?: number;
  ParentTaskId?: number;
  PredecessorIds?: string;
  Priority?: string;
  Progress?: number;
  ProjectId?: number;
  StartDate?: string;
  Status?: string;
  TaskOrder?: number;
  Title?: string;
}

export interface projecthub_sp_UpdateTaskResponse {
  returncode?: number;
  outputparameters?: Record<string, unknown>;
  ResultSets?: {
    Table1?: {
      Id?: number;
      Title?: string;
      Description?: string;
      ProjectId?: number;
      ProjectName?: string;
      ParentTaskId?: number;
      PredecessorIds?: string;
      AssignedTo?: string;
      Status?: string;
      Priority?: string;
      StartDate?: string;
      EndDate?: string;
      DueDate?: string;
      EstimatedHours?: number;
      ActualHours?: number;
      Progress?: number;
      TaskOrder?: number;
      CreatedDate?: string;
      LastModified?: string;
      HasChildren?: number;
      Level?: number;
    }[];
  };
}
