/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

export type projecthub_sp_GetRecentActivityRequest = Record<string, unknown>;

export interface projecthub_sp_GetRecentActivityResponse {
  returncode?: number;
  outputparameters?: Record<string, unknown>;
  ResultSets?: Record<string, unknown>;
}
