/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

export interface projecthub_sp_SearchClientsRequest {
  CompanyFilter?: string;
  PageNumber?: number;
  PageSize?: number;
  SearchTerm?: string;
  SortColumn?: string;
  SortDirection?: string;
  Status?: string;
  TotalRecords?: number;
}

export interface projecthub_sp_SearchClientsResponse {
  returncode?: number;
  outputparameters?: {
    TotalRecords?: number;
  };
  ResultSets?: {
    Table1?: {
      Id?: number;
      Name?: string;
      ContactPerson?: string;
      Email?: string;
      Phone?: string;
      Company?: string;
      Address?: string;
      City?: string;
      State?: string;
      ZipCode?: string;
      Country?: string;
      Industry?: string;
      Notes?: string;
      Status?: string;
      CreatedDate?: string;
      LastModified?: string;
      ProjectCount?: number;
    };
  };
}
